Option for all content area's to be the height of the tallest created
adaptlearning/adapt-contrib-narrative pull request #177
Opened 2017-08-16 14:45 UTC by canstudios-louisem

This gives an option for all content areas to be the same height. This defaults to false so any existing components won't be affected.

2018-03-12 15:05 UTC, moloko requested changes
README and example.json need updating with the new setting

2018-03-12 15:05 UTC, moloko commented on js/adapt-contrib-narrative.js
> +                contentAreas.each(function() {
`.height()` uses implicit iteration so you don't need an `.each()` here, you can just do:
```js
contentAreas.height(maxHeight);
```
or even
```js
contentAreas.each(function() {
    if($(this).height() > maxHeight){
        maxHeight = $(this).height();
    }
}).height(maxHeight);
```

2018-03-12 15:05 UTC, moloko commented on js/adapt-contrib-narrative.js
> +            if(this.model.get('_hasFixedHeightContentArea')){
I think this code block would be better separated out into a function

2018-03-12 15:26 UTC, tomgreenfield commented on js/adapt-contrib-narrative.js
> +                var contentAreas = this.$el.find('.narrative-content-body');
Selectors are already scoped on the view so can be written as just
```javascript
this.$('.narrative-content-body')
```
Could you prefix the variable with a `$` too please?

2018-03-14 07:21 UTC, lc-thomasberger commented
I have not tested this and it will probaly require a restructure and restyling, but there might be a css only implementation with flexbox or css grid layout for sure. It might not work exactly the same on IE ... but I think this should be fine.

2018-10-08 12:28 UTC, moloko commented
closing due to inactivity

2018-10-08 12:28 UTC, closed without merging