ADAPT-7825 - Narrative component issues on mobile
adaptlearning/adapt-contrib-narrative pull request #205
Opened 2021-01-11 16:16 UTC by eleanor-heath

Description of issue:

Customer has reported that When testing two modules) on an Iphone 8. She is having issues with the narrative and hot graphic components - when trying to tap the + to expand the text it is greyed out and on some of them the + to expand disappears completely.

This only happens after the first narrative/graphic and is only happening when I do the modules on an Iphone 8, XS, 11 and 12. It's happening on all of them. I've tried on a number of Android and It's not happening. It's an iPhone specific problem.

2021-01-11 16:35 UTC, ethan-lp approved these changes
👀

2021-01-11 20:20 UTC, oliverfoster commented on js/narrativeView.js
> +      if (this.isLargeMode()) {
Can you put it all in the large mode if block?

2021-01-12 09:13 UTC, cahirodoherty-learningpool approved these changes
👀

2021-01-12 10:01 UTC, oliverfoster approved these changes

2021-01-12 10:05 UTC, moloko commented on js/narrativeView.js
> +      if (this.isLargeMode()) {
sorry to jump in right at the end but you could merge line 188 with 186 and return early i.e. 
```js
      if (this._isInitial || !this.isLargeMode()) return;
```

2021-01-12 10:12 UTC, oliverfoster commented on js/narrativeView.js
> -      const $elementToFocus = this.isLargeMode() ? this.$(`.narrative__content-item[data-index="${itemIndex}"]`) : this.$('.narrative__strapline-btn');
Was it perhaps that `this.$('.narrative__strapline-btn')` should also have an index selector.
Slightly concerned that you're removing the focus on the strapline button after the click.
Have you tested this on iphone with voiceover on to see how it behaves?

2021-01-12 10:18 UTC, eleanor-heath commented on js/narrativeView.js
> -      const $elementToFocus = this.isLargeMode() ? this.$(`.narrative__content-item[data-index="${itemIndex}"]`) : this.$('.narrative__strapline-btn');
I haven't tested it with voiceover, I did try adding in the data index e.g. `this.$('.narrative__strapline-btn')[data-index="${itemIndex}"]` but this was still causing issues as the transform had not completed on the strapline button on IOS devices (line 184). It would work if I place a timeout function after line 186 to allow for the transform to complete, I think it is possibly a known issue with IOS devices: https://stackoverflow.com/questions/30712632/css-transform-only-not-working-on-ios.

2021-01-12 10:21 UTC, eleanor-heath commented on js/narrativeView.js
> -      const $elementToFocus = this.isLargeMode() ? this.$(`.narrative__content-item[data-index="${itemIndex}"]`) : this.$('.narrative__strapline-btn');
I also tried what was suggested in that stackoverflow answer to do translate3d instead of just translateX but that still was not adequate to fix the issue.

2021-01-12 10:32 UTC, oliverfoster commented on js/narrativeView.js
> -      const $elementToFocus = this.isLargeMode() ? this.$(`.narrative__content-item[data-index="${itemIndex}"]`) : this.$('.narrative__strapline-btn');
It sound like the parent is scrolling as the focus is set to the right / left onto an element its overflow space. 

What happens if you just add a _.delay to the focus, enough so that the button on which to focus is at least in the visible area of the parent? 100ms perhaps?

2021-01-12 11:14 UTC, tomgreenfield commented on js/narrativeView.js
> -      const $elementToFocus = this.isLargeMode() ? this.$(`.narrative__content-item[data-index="${itemIndex}"]`) : this.$('.narrative__strapline-btn');
If Ollie's assumptions are correct, could look into using `.one('transitionend', () => {})` instead of a magic number.

2021-01-12 11:32 UTC, eleanor-heath commented on js/narrativeView.js
> -      const $elementToFocus = this.isLargeMode() ? this.$(`.narrative__content-item[data-index="${itemIndex}"]`) : this.$('.narrative__strapline-btn');
@oliverfoster @tomgreenfield this adjustment works, thanks for both of your input!

2021-01-12 11:33 UTC, oliverfoster commented on js/narrativeView.js
> -      const $elementToFocus = this.isLargeMode() ? this.$(`.narrative__content-item[data-index="${itemIndex}"]`) : this.$('.narrative__strapline-btn');
That would assume that the css always had a transition animation. Which I'm not sure we can assume?

2021-01-12 11:37 UTC, eleanor-heath commented on js/narrativeView.js
> -      const $elementToFocus = this.isLargeMode() ? this.$(`.narrative__content-item[data-index="${itemIndex}"]`) : this.$('.narrative__strapline-btn');
both the delay and transitionend functions work, not sure which is best to use?

2021-01-12 11:37 UTC, oliverfoster commented on js/narrativeView.js
> +        this.$(`.narrative__strapline-btn${dataIndexAttr}`);
```suggestion
          this.$(`.narrative__content-item${dataIndexAttr}`) :
          this.$(`.narrative__strapline-btn${dataIndexAttr}`);
```
Indent

2021-01-12 11:41 UTC, tomgreenfield commented on js/narrativeView.js
> -      const $elementToFocus = this.isLargeMode() ? this.$(`.narrative__content-item[data-index="${itemIndex}"]`) : this.$('.narrative__strapline-btn');
> 
> 
> That would assume that the css always had a transition animation. Which I'm not sure we can assume?

If you wanted to specifically check and not just assume:
```js
$straplineHeaderElm.css('transitionDuration') !== '0s'
```

2021-01-12 11:58 UTC, oliverfoster requested changes

2021-01-12 11:58 UTC, oliverfoster commented on js/narrativeView.js
> +          focusOnNarrativeElement(itemIndex);
```suggestion
          this.focusOnNarrativeElement(itemIndex);
```

2021-01-12 11:58 UTC, oliverfoster commented on js/narrativeView.js
> +        focusOnNarrativeElement(itemIndex);
```suggestion
        this.focusOnNarrativeElement(itemIndex);
```

2021-01-12 12:29 UTC, oliverfoster commented on js/narrativeView.js
> +      }
```suggestion
      const hasStraplineTransition = !this.isLargeMode() && parseFloat($straplineHeaderElm.css('transitionDuration'));
      if (hasStraplineTransition) {
        $straplineHeaderElm.one('transitionend', () => {
          this.focusOnNarrativeElement(itemIndex);
        });
      } else {
        this.focusOnNarrativeElement(itemIndex);
      }
```
Without the isLarge check in large mode it'll always try to wait for the strapline to finish animating, but it never will, so we're just queuing up lots of once event handlers which never callback.
parseFloat is just to check there is any numeric value larger than 0, regardless of unit.

2021-01-12 14:43 UTC, oliverfoster approved these changes

2021-01-12 14:50 UTC, eleanor-heath commented
@tomgreenfield @moloko can you re-review please

2021-01-12 15:41 UTC, tomgreenfield approved these changes
Just a code skim; I haven't an iPhone to test on.

Version also needs bumping in README before release.

2021-01-12 15:41 UTC, oliverfoster commented on js/narrativeView.js
> +      const hasStraplineTransition = !this.isLargeMode() && parseFloat($straplineHeaderElm.css('transitionDuration'));
```suggestion
      const hasStraplineTransition = !this.isLargeMode() && ($straplineHeaderElm.css('transitionDuration') !== '0s');
```
Sorry to be a complete * cough * but @tomgreenfield has convinced me that your original comparison was more appropriate.
It results in a boolean and `$straplineHeaderElm.css('transitionDuration')` is always normalised to `0s` for `0ms` or `0.0000ms` or `undefined`.

2021-01-12 15:53 UTC, oliverfoster approved these changes

2021-01-14 16:39 UTC, moloko commented on README.md
> +**Cross-platform coverage:** Chrome, Chrome for Android, Firefox (ESR + latest version), Edge, IE11, Safari 12+13 for macOS/iOS/iPadOS, Opera
Just updating this as we do new releases

```suggestion
**Cross-platform coverage:** Chrome, Chrome for Android, Firefox (ESR + latest version), Edge, IE11, Safari 14 for macOS/iOS/iPadOS, Opera
```

2021-01-14 16:39 UTC, moloko commented on README.md
> +**Version number:**  6.2.1   <a href="https://community.adaptlearning.org/" target="_blank"><img src="https://github.com/adaptlearning/documentation/blob/master/04_wiki_assets/plug-ins/images/adapt-l
could you put the trailing spaces back on these lines? removing them has caused a change in layout
![image](https://user-images.githubusercontent.com/1249597/104620274-b8be0780-5686-11eb-8964-50f9138a4547.png)

(equally a <br> tag would work just as well and arguably make the intent clearer)

2021-01-14 16:41 UTC, moloko commented on js/narrativeView.js
> +      } else {
`return` early and remove the need for the `else` block?

2021-01-14 17:28 UTC, tomgreenfield commented on README.md
> +    (This second method will reinstall all plug-ins listed in *adapt.json*.)
Your editor has causeD the formatting to be lost here. Suggest:
~~~suggestion
  ```console
  adapt install adapt-contrib-narrative
  ```
  Alternatively, this component can also be installed by adding the following line of code to the *adapt.json* file:
  ```json
  "adapt-contrib-narrative": "*"
  ```
  Then running the command:
  ```console
  adapt install
  ```
  (This second method will reinstall all plug-ins listed in *adapt.json*.)
~~~

2021-01-15 10:58 UTC, oliverfoster commented on js/narrativeView.js
> +          return;
It should be where it was.

2021-01-15 11:04 UTC, tomgreenfield commented on README.md
> +    (This second method will reinstall all plug-ins listed in *adapt.json*.)
Sorry, would you mind copying the suggested snippet as-is?

(The two-space indentation is important to retain the current formatting under the bullet point and
the added `<br>` tags are not required because the code sections are now blocks rather than inline.)

2021-01-15 11:23 UTC, moloko approved these changes
need to remove a few `<br>` tags from the README.md but otherwise looks good

2021-01-15 11:23 UTC, moloko commented on README.md
> +# adapt-contrib-narrative<br>
`<br>` not required here as it's already heading level 1

2021-01-15 11:23 UTC, moloko commented on README.md
> +**instruction** (string): This optional text appears above the component. It is frequently used to guide the learner’s interaction with the component.<br>
`<br>` not required here as the blank line at L48 is already sufficient

2021-01-15 11:23 UTC, moloko commented on README.md
> +### Accessibility<br>
`<br>` not required here as it's already heading level 3

2021-01-15 11:23 UTC, moloko commented on README.md
> +**mobileInstruction** (string): This is optional instruction text that will be shown when viewed on mobile. It may be used to guide the learner’s interaction with the component.<br>
`<br>` not required here as the blank line at L50 is already sufficient

2021-01-15 11:26 UTC, tomgreenfield commented on README.md
> +    (This second method will reinstall all plug-ins listed in *adapt.json*.)
Added `<br>` tag not required on line 16.

2021-01-18 12:15 UTC, moloko approved these changes

2021-01-18 12:35 UTC, oliverfoster approved these changes

2021-01-18 13:56 UTC, tomgreenfield commented on README.md
> +**Narrative** is a *presentation component* bundled with the [Adapt framework](https://github.com/adaptlearning/adapt_framework).<br>
```suggestion
**Narrative** is a *presentation component* bundled with the [Adapt framework](https://github.com/adaptlearning/adapt_framework).
```

2021-01-18 13:56 UTC, tomgreenfield commented on README.md
> +* If **Narrative** has been uninstalled from the Adapt authoring tool, it may be reinstalled using the [Plug-in Manager](https://github.com/adaptlearning/adapt_authoring/wiki/Plugin-Manager).<br>
```suggestion
* If **Narrative** has been uninstalled from the Adapt authoring tool, it may be reinstalled using the [Plug-in Manager](https://github.com/adaptlearning/adapt_authoring/wiki/Plugin-Manager).
```

2021-01-18 13:56 UTC, tomgreenfield commented on README.md
> +>**strapline** (string): This text is displayed as a title above the image when `Adapt.device.screenSize` is `small` (i.e., when viewed on mobile devices).<br>
```suggestion
>**strapline** (string): This text is displayed as a title above the image when `Adapt.device.screenSize` is `small` (i.e., when viewed on mobile devices).
```

2021-01-18 13:56 UTC, tomgreenfield commented on README.md
> +**Cross-platform coverage:** Chrome, Chrome for Android, Firefox (ESR + latest version), Edge, IE11, Safari 14 for macOS/iOS/iPadOS, Opera<br>
```suggestion
**Cross-platform coverage:** Chrome, Chrome for Android, Firefox (ESR + latest version), Edge, IE11, Safari 14 for macOS/iOS/iPadOS, Opera
```

2021-01-18 13:56 UTC, tomgreenfield commented on README.md
> +**Narrative** has been assigned a label using the [aria-label](https://github.com/adaptlearning/adapt_framework/wiki/Aria-Labels) attribute: **ariaRegion**. This label is not a visible element. It is
```suggestion
**Narrative** has been assigned a label using the [aria-label](https://github.com/adaptlearning/adapt_framework/wiki/Aria-Labels) attribute: **ariaRegion**. This label is not a visible element. It is utilized by assistive technology such as screen readers. Should the region's text need to be customised, it can be found within the **globals** object in [*properties.schema*](https://github.com/adaptlearning/adapt-contrib-narrative/blob/master/properties.schema).
```

2021-01-20 14:28 UTC, eleanor-heath commented
This has now come back from QA and is marked for release @cahirodoherty-learningpool

2021-01-20 14:29 UTC, tomgreenfield approved these changes
:eye:

2021-01-20 14:31 UTC, merged