Full width items custom class support
adaptlearning/adapt-contrib-narrative pull request #215
Opened 2021-05-27 11:47 UTC by guywillis

Resolves https://github.com/adaptlearning/adapt_framework/issues/3160

* Adds a custom class to increase the size of the narrative items to 100% for desktop view

2021-05-27 12:09 UTC, eleanor-heath approved these changes

2021-06-01 10:41 UTC, oliverfoster requested changes

2021-06-01 10:41 UTC, oliverfoster commented on README.md
> +**\_classes** (string): CSS class name to be applied to **Narrative**’s containing div. Supported class is `items-are-full-width` which increases the width of the narrative elements to 100% in deskto
```suggestion
**\_classes** (string): CSS class name to be applied to **Narrative**’s containing div. The class must be predefined in one of the Less files. Separate multiple classes with a space. `items-are-full-width` increases the width of the narrative elements to 100% in desktop view.
```

2021-06-01 11:46 UTC, guywillis commented on README.md
> +**\_classes** (string): CSS class name to be applied to **Narrative**’s containing div. Supported class is `items-are-full-width` which increases the width of the narrative elements to 100% in deskto
Updated

2021-06-02 09:40 UTC, oliverfoster approved these changes

2021-06-02 09:40 UTC, merged