issue/1029 Narrative ES6 and text below image
adaptlearning/adapt-contrib-narrative pull request #217
Opened 2021-06-22 09:13 UTC by oliverfoster

2021-06-24 10:26 UTC, guywillis approved these changes
👀

2021-06-28 11:28 UTC, cahirodoherty-learningpool requested changes

2021-06-28 11:28 UTC, cahirodoherty-learningpool commented on README.md
> +**\_isTextBelowImage** (boolean): If enabled, the text area drops below the image instead of being aside it.
Minor: ~aside~ 'beside'

2021-06-29 09:44 UTC, cahirodoherty-learningpool approved these changes
👀

2021-06-29 09:47 UTC, ethan-lp approved these changes
👀

2021-06-29 10:36 UTC, merged