issue/2799 Removed redundant behaviour
adaptlearning/adapt-contrib-narrative pull request #224
Opened 2022-03-24 12:53 UTC by oliverfoster

requires https://github.com/adaptlearning/adapt-contrib-core/pull/84
part of https://github.com/adaptlearning/adapt_framework/issues/2799

### Changed
* Switched to components.register from Adapt.register
* Use `a11y`, `device` and `notify` directly

2022-03-29 10:33 UTC, cahirodoherty-learningpool approved these changes
👀

2022-04-28 16:11 UTC, joe-allen-89 requested changes
Duplicate import device.

2022-04-28 16:11 UTC, joe-allen-89 commented on js/NarrativeView.js
>  import device from 'core/js/device';
Need to remove the duplicate import device.

2022-05-09 09:30 UTC, eleanor-heath approved these changes

2022-05-23 11:17 UTC, oliverfoster commented on js/NarrativeView.js
>  import device from 'core/js/device';
Weird that I keep doing that.

2022-05-23 11:29 UTC, merged