resolve page scroll when user selects last item
adaptlearning/adapt-contrib-narrative pull request #232
Opened 2022-07-18 14:03 UTC by chris-steele

To resolve #231

2022-07-19 08:46 UTC, oliverfoster commented
Could you try removing these instead please?

https://github.com/adaptlearning/adapt-contrib-narrative/blob/268cf26e4a1f8a67a6841b4cea922acfba300d6c/js/NarrativeView.js#L273-L274

2022-07-19 11:54 UTC, oliverfoster requested changes
See suggestion

2022-07-21 09:45 UTC, guywillis commented
Both solutions resolve the page jump.

The suggestion from Ollie displays the previous button on the first slide and the next button on the last slide. Whilst selecting these buttons causes no errors within the build it is potentially confusing from a UI perspective and almost certainly confusing from a screen reader perspective - the buttons can be tabbed into and are read out.

Tested with NVDA.

2022-07-24 11:13 UTC, oliverfoster commented
> Both solutions resolve the page jump.
> 
> The suggestion from Ollie displays the previous button on the first slide and the next button on the last slide. Whilst selecting these buttons causes no errors within the build it is potentially confusing from a UI perspective and almost certainly confusing from a screen reader perspective - the buttons can be tabbed into and are read out.
> 
> Tested with NVDA.

They should be read out as disabled.

2022-07-28 09:43 UTC, oliverfoster commented
@guywillis Let us know about the nvda disabled bugs when you get a chance pls

2022-07-29 10:53 UTC, guywillis commented
NVDA does not read the buttons as disabled. 

When testing, I have only removed these two lines as mentioned above:

> https://github.com/adaptlearning/adapt-contrib-narrative/blob/268cf26e4a1f8a67a6841b4cea922acfba300d6c/js/NarrativeView.js#L273-L274
> 

Screenshot of the narrative controls in the DOM for the first item of three.

<img width="429" alt="Screenshot 2022-07-29 at 11 50 42" src="https://user-images.githubusercontent.com/11569678/181744278-897ff0cb-f807-41e1-a6cb-b06f230d3f7a.png">

2022-08-01 09:51 UTC, oliverfoster commented
@chris-steele can you replace 

https://github.com/adaptlearning/adapt-contrib-narrative/blob/268cf26e4a1f8a67a6841b4cea922acfba300d6c/js/NarrativeView.js#L273-L274

with 

```js
    a11y.toggleEnabled($left, !isAtStart);
    a11y.toggleEnabled($right, !isAtEnd);
```

instead?

2022-08-01 13:43 UTC, guywillis commented
Works a charm.

Tested with NVDA

2022-08-01 15:31 UTC, chris-steele commented
Done and thanks both

2022-08-02 08:47 UTC, oliverfoster commented on js/NarrativeView.js
> +
```suggestion
```
Please remove

2022-08-08 08:02 UTC, oliverfoster approved these changes

2022-08-08 08:29 UTC, cahirodoherty-learningpool approved these changes
👀

2022-08-08 10:01 UTC, merged